// Code generated by mockery v1.0.0
package mocks

import mock "github.com/stretchr/testify/mock"

// ColorHelperInterface is an autogenerated mock type for the ColorHelperInterface type
type ColorHelperInterface struct {
	mock.Mock
}

// GetRandomColors provides a mock function with given fields: num_of_colors
func (_m *ColorHelperInterface) GetRandomColors(num_of_colors int) []string {
	ret := _m.Called(num_of_colors)

	var r0 []string
	if rf, ok := ret.Get(0).(func(int) []string); ok {
		r0 = rf(num_of_colors)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]string)
		}
	}

	return r0
}
